env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
  - '@typescript-eslint'
rules: {
  "semi": ["error", "always"],
  "semi-spacing": ["error", {"after": true, "before": false}],
  "semi-style": ["error", "last"],
  "no-extra-semi": "error",
}
